version: '3.4'

services:
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: 'authentication_authorization'
      MYSQL_USER: 'db_user'
      MYSQL_ROOT_PASSWORD: 'db_password1234'  
    volumes:
      - db-config:/etc/mysql
      - my-db:/var/lib/mysql

  authenticationauthorization:
    image: authenticationauthorization
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_TYPE: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: authentication_authorization
      DB_USERNAME: db_user
      DB_PASSWORD: db_password1234

    ports:
      - 8000:8000

volumes:
  my-db:
  db-config: