export enum AuthorizationPermissionEnum {
    AUTHORIZATION_ROLE_READ = 'AUTHORIZATION_ROLE_READ',
    AUTHORIZATION_ROLE_CREATE = 'AUTHORIZATION_ROLE_CREATE',
    AUTHORIZATION_ROLE_UPDATE = 'AUTHORIZATION_ROLE_UPDATE',
    AUTHORIZATION_ROLE_DELETE = 'AUTHORIZATION_ROLE_DELETE',
    AUTHORIZATION_PERMISSION_READ = 'AUTHORIZATION_PERMISSION_READ',
    AUTHORIZATION_CHANGE_ACCESSIBILITY = 'AUTHORIZATION_CHANGE_ACCESSIBILITY',
    AUTHORIZATION_ASSIGN_ROLE = 'AUTHORIZATION_ASSIGN_ROLE',
}